apiVersion: v1
kind: Secret
metadata:
  namespace: chest-ct
  name: s3-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: bHh6WlRGTzRvMlc2OEZ6bkVmR1Q=
  AWS_SECRET_ACCESS_KEY: Q1dZdnh2NkcxRFFwUExUM05DdXdiYmJxTnp6MXJBaE9IekFHa2E3ZQ==
  MLFLOW_S3_ENDPOINT_URL: aHR0cHM6Ly9zMy5taW5pby5jb21wYW55Lms4cw==
  MLFLOW_S3_IGNORE_TLS: dHJ1ZQ==
