apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-pod
spec:
  containers:
    - name: configmap-demo-pod
      image: alpine
      command: ["sleep", "3600"]
      env:
        # Define the environment variable
        - name: APP_COLOR       # Notice that the case is different here from the key name in the ConfigMap.
          valueFrom:
            configMapKeyRef:
              name: game-demo   # The ConfigMap this value comes from.
              key: APP_COLOR    # The key to fetch.
        - name: APP_MODE
          valueFrom:
            configMapKeyRef:
              name: game-demo
              key: APP_MODE
      volumeMounts:
      - name: config
        mountPath: "/config"
        readOnly: true
  volumes:
  # You set volumes at the Pod level, then mount them into containers inside that Pod
  - name: config
    configMap:
      # Provide the name of the ConfigMap you want to mount.
      name: game-demo
      # An array of keys from the ConfigMap to create as files
      items:
      - key: "game.properties"
        path: "game.properties"
      - key: "user-interface.properties"
        path: "user-interface.properties"