apiVersion: v1
kind: Pod
metadata:
  name: secret-envfrom-pod
spec:
  containers:
    - name: secret-envfrom-pod
      image: alpine
      command: ["sleep", "3600"]
      envFrom:
        - secretRef:
            name: secret-basic-auth