apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
    - name: secret-env-pod
      image: alpine
      command: ["sleep", "3600"]
      env:
        - name: DB_PWD
          valueFrom:
            secretKeyRef:
              name: secret-basic-auth
              key: password
          